application: granary-demo
version: 1
threadsafe: true
api_version: 1
default_expiration: 1d

runtime: python27

libraries:
- name: ssl
  version: latest

handlers:
- url: /(static/bootstrap.*\.css)
  static_files: local/lib/python2.7/site-packages/oauth_dropins/\1
  upload: local/lib/python2.7/site-packages/oauth_dropins/static/bootstrap.*\.css

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /oauth_dropins/static
  static_dir: local/lib/python2.7/site-packages/oauth_dropins/static

- url: /fonts
  static_dir: local/lib/python2.7/site-packages/oauth_dropins/fonts

- url: /(.well-known/.*)?
  script: app.application
  secure: always

- url: /(start_auth|twitter/oauth_callback)
  script: app.application
  secure: always

- url: /.+
  script: activitystreams.application
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|docs?|examples?|pydocs?|python3|ref|samples?|tests?)/.*
